import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Inter, Marck_Script } from "next/font/google";
import Heart from "../shared/HeartEffect";
import "./globals.css";

const inter = Inter({
  subsets: ["latin", "cyrillic"],
});
const marck_Script = Marck_Script({
  subsets: ["latin", "cyrillic"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Shamil-love",
  description: "Generated by create next app",
};
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${marck_Script.className}`}>
        <Heart />
        {children}
      </body>
    </html>
  );
}
